{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2024-04-25T12:43:07.545976Z",
     "start_time": "2024-04-25T12:43:07.508193Z"
    }
   },
   "outputs": [],
   "source": [
    "from mbientlab.metawear import MetaWear, libmetawear\n",
    "from mbientlab.metawear.cbindings import *\n",
    "from ctypes import c_void_p, POINTER, CFUNCTYPE\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "outputs": [],
   "source": [
    "# MAC address of the MetaWear device\n",
    "device_address = 'D4:06:BD:85:8F:23'\n",
    "\n",
    "# Create and connect the device\n",
    "device = MetaWear(device_address)\n",
    "device.connect()"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-04-25T12:43:14.279181Z",
     "start_time": "2024-04-25T12:43:07.926291Z"
    }
   },
   "id": "8356ecdc5c8c5981",
   "execution_count": 20
  },
  {
   "cell_type": "code",
   "outputs": [],
   "source": [
    "data_list = []\n",
    "\n",
    "# Callback function to handle incoming data\n",
    "def data_handler(context, data):\n",
    "    # Convert the data pointer to a usable format, assuming it's CartesianFloat for demonstration\n",
    "    if data.contents.type_id == DataTypeId.CARTESIAN_FLOAT:\n",
    "        value = cast(data.contents.value, POINTER(CartesianFloat)).contents\n",
    "        timestamp = int(data.contents.epoch)\n",
    "        sensor = context.decode('utf-8')\n",
    "        print(\"Sensor: %.2f Timestamp: %.2f X: %.2f Y: %.2f Z: %.2f\" % (sensor, timestamp, value.x, value.y, value.z))\n",
    "        data_list.append([timestamp, value.x, value.y, value.z])\n",
    "        \n",
    "        \n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-04-25T12:43:17.637853Z",
     "start_time": "2024-04-25T12:43:17.631039Z"
    }
   },
   "id": "a2b0ca160b05e515",
   "execution_count": 21
  },
  {
   "cell_type": "code",
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n",
      "AttributeError: 'NoneType' object has no attribute 'decode'\n",
      "Exception ignored on calling ctypes callback function: <function data_handler at 0x000002811939D580>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jelte\\AppData\\Local\\Temp\\ipykernel_26424\\3904960911.py\", line 9, in data_handler\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Disconnected and cleaned up\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Define the callback type\n",
    "FnVoid_VoidP_DataP = CFUNCTYPE(None, c_void_p, POINTER(Data))\n",
    "\n",
    "# Setup callback\n",
    "callback = FnVoid_VoidP_DataP(data_handler)\n",
    "\n",
    "# Configure accelerometer\n",
    "libmetawear.mbl_mw_acc_set_odr(device.board, 100.0)  # Set output data rate to 100 Hz\n",
    "libmetawear.mbl_mw_acc_set_range(device.board, 16.0)  # Set range to +/-16g\n",
    "libmetawear.mbl_mw_acc_write_acceleration_config(device.board)\n",
    "\n",
    "# Get the accelerometer data signal\n",
    "acc_signal = libmetawear.mbl_mw_acc_get_acceleration_data_signal(device.board)\n",
    "\n",
    "\n",
    "\n",
    "libmetawear.mbl_mw_gyro_bmi160_write_config(device.board)\n",
    "gyro_signal = libmetawear.mbl_mw_gyro_bmi160_get_rotation_data_signal(device.board)\n",
    "\n",
    "\n",
    "\n",
    "# Subscribe to the accelerometer data signal\n",
    "libmetawear.mbl_mw_datasignal_subscribe(acc_signal, None, callback, \"acc\".encode('utf-8'))\n",
    "libmetawear.mbl_mw_datasignal_subscribe(gyro_signal, None, callback, \"gyro\".encode('utf-8'))\n",
    "\n",
    "\n",
    "# Enable accelerometer\n",
    "libmetawear.mbl_mw_acc_enable_acceleration_sampling(device.board)\n",
    "libmetawear.mbl_mw_acc_start(device.board)\n",
    "libmetawear.mbl_mw_gyro_bmi160_enable_rotation_sampling(device.board)\n",
    "libmetawear.mbl_mw_gyro_bmi160_start(device.board)\n",
    "\n",
    "# Stream data for a duration (e.g., 30 seconds)\n",
    "time.sleep(5)\n",
    "\n",
    "# Stop and clean up\n",
    "libmetawear.mbl_mw_acc_stop(device.board)\n",
    "libmetawear.mbl_mw_acc_disable_acceleration_sampling(device.board)\n",
    "libmetawear.mbl_mw_datasignal_unsubscribe(acc_signal)\n",
    "libmetawear.mbl_mw_debug_disconnect(device.board)\n",
    "print(\"Disconnected and cleaned up\")"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-04-25T12:43:23.665630Z",
     "start_time": "2024-04-25T12:43:18.643354Z"
    }
   },
   "id": "6c43f826df570e57",
   "execution_count": 22
  },
  {
   "cell_type": "code",
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "we are disconnected!\n"
     ]
    }
   ],
   "source": [
    "device.on_disconnect = lambda status: print (\"we are disconnected!\")\n",
    "device.disconnect()"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-04-25T08:03:14.515781Z",
     "start_time": "2024-04-25T08:03:14.510111Z"
    }
   },
   "id": "95844a5ae8c68495",
   "execution_count": 15
  },
  {
   "cell_type": "code",
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001B[1;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[1;31mIndexError\u001B[0m                                Traceback (most recent call last)",
      "Cell \u001B[1;32mIn[23], line 2\u001B[0m\n\u001B[0;32m      1\u001B[0m \u001B[38;5;28;01mfor\u001B[39;00m i \u001B[38;5;129;01min\u001B[39;00m \u001B[38;5;28mrange\u001B[39m(\u001B[38;5;241m100\u001B[39m):\n\u001B[1;32m----> 2\u001B[0m     \u001B[38;5;28mprint\u001B[39m(\u001B[43mdata_list\u001B[49m\u001B[43m[\u001B[49m\u001B[43mi\u001B[49m\u001B[43m]\u001B[49m)\n",
      "\u001B[1;31mIndexError\u001B[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "for i in range(100):\n",
    "    print(data_list[i])"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2024-04-25T12:43:31.625912Z",
     "start_time": "2024-04-25T12:43:31.465492Z"
    }
   },
   "id": "9bde011562bc603f",
   "execution_count": 23
  },
  {
   "cell_type": "code",
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   },
   "id": "4162e79e9bebd46d"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
